// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {MxObject} bomLine
 * @param {MxObject} fileDocument
 * @param {string} parentPsId
 * @returns {Promise.<string>}
 */
export async function JS_AddBOMLineToViewer(bomLine, fileDocument, parentPsId) {
	// BEGIN USER CODE
	return new Promise((resolve, reject)=> {
		let viewer = document.getElementById("visualizationWidget1").viewerManager;
		if (viewer !== undefined) {
			let dacManager = viewer.getDACManager();
			let nodePsId;
			if (fileDocument) {
				let fileDocumentPath = mx.appUrl + "file?guid=" + fileDocument.getGuid() + "&changedDate=" + fileDocument.get("changedDate");
				let transform = bomLine.get("bl_plmxml_abs_xform");
				let xformArray = transform.split(" ").map(Number);
				nodePsId = dacManager.createNode({
					title: bomLine.get("bl_rev_object_name"),
					parent: parentPsId,
					units: window.PLMVisWeb.Units.METER,
					fileRef: { url: fileDocumentPath, query: true},
					xform: xformArray
				});
				viewer.setVisibilityByPsId(nodePsId, true, () => {
					viewer.fitToModel();
					resolve(nodePsId);
				});
			} else {
				nodePsId = dacManager.createNode({
					title: bomLine.get("bl_rev_object_name"),
					parent: parentPsId,
					units: window.PLMVisWeb.Units.MILLIMETER
				});
				resolve(nodePsId);
			}
		} else {
			reject();
		}
	});
	// END USER CODE
}
