// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_ClearViewer() {
	// BEGIN USER CODE
	return new Promise((resolve, reject)=> {
		let viewer = document.getElementById("visualizationWidget1").viewerManager;
		if (viewer !== undefined) {
			viewer.clearScene();
			resolve();
		} else {
			reject();
		}
	});
	// END USER CODE
}
